name: GitHub Actions Demo
run-name: testing
on: [push]
jobs:
  Trial:
    runs-on: Ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt install python3
      - run: pip install awscli
      - run: aws --version
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: aws configure set region $AWS_DEFAULT_REGION
      - run: aws s3 cp ./ s3://jenforms
